---
driver:
  name: dokken
  privileged: true
  chef_version: 12.19.36
  hostname: test.introhive.com

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    platform: ubuntu
    pid_one_command: /bin/systemd
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
  - name: sensu-server
    run_list:
      - recipe[ih_sensu::default]
      - recipe[ih_sensu::rabbitmq]
      - recipe[ih_sensu::redis]
      - recipe[ih_sensu::server]
    excludes:
      - ubuntu-14.04
      
