#sudo: true
sudo: false
language: ruby
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-xenial

# Don't `bundle install`
install: echo "skip bundle install"
services: docker

#env:
#  matrix:
#  - INSTANCE=default-ubuntu-1604
#  - INSTANCE=default-ubuntu-1404

before_script:
#  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk -v 1.3
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/gem install chef -v '12.19.36'
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

#script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec rspec
