#sudo: true
sudo: false
language: ruby
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-xenial

# Don't `bundle install`
install: echo "skip bundle install"
services: docker

env:
  global:
    - KITCHEN_YAML=.kitchen.yml
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  matrix:
    - INSTANCE=default-ubuntu-1604

#env:
#  matrix:
#  - INSTANCE=default-ubuntu-1604
#  - INSTANCE=default-ubuntu-1404

before_script:
#  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - wget https://packages.chef.io/files/stable/chefdk/1.4.3/debian/8/chefdk_1.4.3-1_amd64.deb
  - sudo dpkg -i chefdk_1.4.3-1_amd64.deb
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/gem install chef -v '12.19.36'
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec rspec
